// YouTube Data API adapter — upload a video file to the Develop Coaching channel.
// YouTube auto-classifies vertical clips <=3min as Shorts (no special flag needed).
//
// Docs: https://developers.google.com/youtube/v3/docs/videos/insert
//
// Required env:
//   YOUTUBE_CLIENT_ID
//   YOUTUBE_CLIENT_SECRET
//   YOUTUBE_REFRESH_TOKEN     (generated by scripts/youtube-oauth.mjs)
//   YOUTUBE_CHANNEL_ID        (informational; the token resolves the channel)
//
// The refresh token needs the `youtube` (manage) scope in addition to
// `youtube.upload` if you want to edit a video after upload (e.g. flip privacy).

import { google } from 'googleapis';
import { createReadStream, existsSync } from 'fs';
import type { PublishResult, QueuePost } from '../types.js';
import { formatCaption } from '../caption.js';

export function youtubeConfigured(): boolean {
  return !!(
    process.env.YOUTUBE_CLIENT_ID &&
    process.env.YOUTUBE_CLIENT_SECRET &&
    process.env.YOUTUBE_REFRESH_TOKEN
  );
}

function ytClient() {
  const auth = new google.auth.OAuth2(
    process.env.YOUTUBE_CLIENT_ID,
    process.env.YOUTUBE_CLIENT_SECRET
  );
  auth.setCredentials({ refresh_token: process.env.YOUTUBE_REFRESH_TOKEN });
  return google.youtube({ version: 'v3', auth });
}

// For YouTube, the post needs a local video path. We stash it on
// post.asset_url ('file://...' or absolute path) since QueuePost doesn't
// have a dedicated video field.
function resolveVideoPath(post: QueuePost): string | null {
  const candidate = post.asset_url || post.image_urls?.[0];
  if (!candidate) return null;
  const path = candidate.replace(/^file:\/\//, '');
  return existsSync(path) ? path : null;
}

export type YouTubePrivacy = 'public' | 'unlisted' | 'private';

export interface UploadVideoOptions {
  videoPath: string;
  title: string;
  description: string;
  tags?: string[];
  privacy?: YouTubePrivacy;
  categoryId?: string;
}

// Low-level upload — full control over title/description/privacy. Both the
// dispatcher path (publishToYouTube) and the CLI (scripts/post-youtube.ts)
// go through here, so there's a single place that talks to the API.
export async function uploadVideo(opts: UploadVideoOptions): Promise<PublishResult> {
  if (!existsSync(opts.videoPath)) {
    return {
      success: false,
      mode: 'youtube',
      error: `Video file not found: ${opts.videoPath}`,
    };
  }

  try {
    const yt = ytClient();
    const res = await yt.videos.insert({
      part: ['snippet', 'status'],
      requestBody: {
        snippet: {
          title: opts.title.slice(0, 100),
          description: opts.description.slice(0, 5000),
          tags: opts.tags?.slice(0, 15),
          categoryId: opts.categoryId || '22', // People & Blogs
        },
        status: {
          privacyStatus: opts.privacy || 'public',
          selfDeclaredMadeForKids: false,
        },
      },
      media: {
        body: createReadStream(opts.videoPath),
      },
    });

    const id = res.data.id;
    if (!id) {
      return {
        success: false,
        mode: 'youtube',
        error: `YouTube upload returned no video id: ${JSON.stringify(res.data)}`,
      };
    }

    return {
      success: true,
      mode: 'youtube',
      externalId: id,
      externalUrl: `https://www.youtube.com/watch?v=${id}`,
    };
  } catch (err: any) {
    return {
      success: false,
      mode: 'youtube',
      error: `YouTube upload failed: ${err.message || String(err)}`,
    };
  }
}

export async function publishToYouTube(post: QueuePost): Promise<PublishResult> {
  const videoPath = resolveVideoPath(post);
  if (!videoPath) {
    return {
      success: false,
      mode: 'youtube',
      error: 'YouTube needs a local video file path on asset_url',
    };
  }

  const formatted = formatCaption('youtube', post.draft_content);
  const lines = formatted.body.split('\n').map((l) => l.trim()).filter(Boolean);
  const title = lines[0] || 'Develop Coaching';

  // Pull #hashtags out of the body as tags too
  const tags = Array.from(formatted.body.matchAll(/#(\w+)/g)).map((m) => m[1]);

  return uploadVideo({
    videoPath,
    title,
    description: formatted.body,
    tags,
    privacy: 'public',
  });
}
