-- Greg Brain Content RAG Schema
-- Supabase project: homnpuxiopsxfsuawzzy
-- Lives alongside Geoffrey bot in the same Supabase instance
-- Uses public schema with greg_ prefix to avoid conflicts

-- Drop old content schema tables if they exist
drop table if exists content.performance_data;
drop table if exists content.content_queue;
drop table if exists content.monthly_calendars;
drop table if exists content.content_chunks;
drop table if exists content.source_documents;
drop function if exists content.hybrid_search;
drop schema if exists content;

-- Enable pgvector extension (may already exist from Geoffrey bot)
create extension if not exists vector;

-- ============================================================
-- Table 1: greg_source_documents
-- Tracks every source file that has been ingested
-- ============================================================
create table if not exists greg_source_documents (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  source_type text not null,  -- 'podcast', 'video', 'book', 'workshop', 'email', 'linkedin'
  file_path text,             -- original file path or URL
  github_path text,           -- if sourced from GitHub repo
  processed_at timestamptz default now(),
  word_count int,
  status text default 'active',  -- 'active', 'archived'
  metadata jsonb              -- episode number, date recorded, platform, etc.
);

-- ============================================================
-- Table 2: greg_content_chunks
-- The actual chunked, embedded content used for RAG retrieval
-- ============================================================
create table if not exists greg_content_chunks (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references greg_source_documents(id),
  chunk_index int not null,
  content text not null,
  embedding vector(1536),       -- OpenAI text-embedding-3-small
  search_vector tsvector,       -- for BM25 keyword search
  topic_tags text[],            -- ['attract', 'pricing', 'architect', etc.]
  framework_tags text[],        -- ['plan', 'attract', 'convert', 'deliver', 'scale']
  created_at timestamptz default now()
);

-- GIN index for full-text search
create index if not exists greg_content_chunks_search_idx on greg_content_chunks using gin(search_vector);

-- Auto-update tsvector on insert/update
drop trigger if exists greg_content_chunks_search_update on greg_content_chunks;
create trigger greg_content_chunks_search_update
  before insert or update on greg_content_chunks
  for each row execute function
  tsvector_update_trigger(search_vector, 'pg_catalog.english', content);

-- ============================================================
-- Table 3: greg_monthly_calendars
-- Stores each monthly content plan generated by the agent
-- ============================================================
create table if not exists greg_monthly_calendars (
  id uuid primary key default gen_random_uuid(),
  month date not null,                -- first day of the month
  generated_at timestamptz default now(),
  themes text[],                      -- main themes the agent chose
  status text default 'draft',        -- 'draft', 'approved', 'published'
  approved_at timestamptz,
  notes text                          -- Chloe's notes
);

-- ============================================================
-- Table 4: greg_content_queue
-- Individual posts generated by the agent, waiting for review
-- ============================================================
create table if not exists greg_content_queue (
  id uuid primary key default gen_random_uuid(),
  calendar_id uuid references greg_monthly_calendars(id),
  platform text not null,            -- 'linkedin', 'email', 'x', 'instagram_caption'
  post_type text,                    -- 'hook_post', 'story_post', 'framework_post', 'carousel'
  draft_content text not null,
  source_chunk_ids uuid[],           -- which chunks from the knowledge base were used
  scheduled_date date,
  status text default 'draft',       -- 'draft', 'approved', 'scheduled', 'published', 'rejected'
  chloe_notes text,
  created_at timestamptz default now(),
  published_at timestamptz
);

-- ============================================================
-- Table 5: greg_performance_data
-- Stores engagement data so the agent can learn what performs well
-- ============================================================
create table if not exists greg_performance_data (
  id uuid primary key default gen_random_uuid(),
  queue_id uuid references greg_content_queue(id),
  platform text not null,
  impressions int,
  engagements int,
  clicks int,
  recorded_at timestamptz default now()
);

-- ============================================================
-- Hybrid Search Function
-- 70% vector / 30% keyword (same pattern as Geoffrey)
-- ============================================================
create or replace function hybrid_search(
  query_text text,
  query_embedding vector(1536),
  match_count int default 10,
  framework_filter text default null,
  topic_filter text default null
)
returns table (
  id uuid,
  content text,
  document_id uuid,
  topic_tags text[],
  framework_tags text[],
  combined_score float
)
language sql stable as $$
  with vector_results as (
    select
      cc.id, cc.content, cc.document_id, cc.topic_tags, cc.framework_tags,
      1 - (cc.embedding <=> query_embedding) as vector_score
    from greg_content_chunks cc
    where
      (framework_filter is null or framework_filter = any(cc.framework_tags))
      and (topic_filter is null or topic_filter = any(cc.topic_tags))
    order by cc.embedding <=> query_embedding
    limit match_count * 2
  ),
  keyword_results as (
    select
      cc.id,
      ts_rank(cc.search_vector, plainto_tsquery('english', query_text)) as keyword_score
    from greg_content_chunks cc
    where cc.search_vector @@ plainto_tsquery('english', query_text)
    limit match_count * 2
  )
  select
    v.id, v.content, v.document_id, v.topic_tags, v.framework_tags,
    (0.7 * v.vector_score + 0.3 * coalesce(k.keyword_score, 0)) as combined_score
  from vector_results v
  left join keyword_results k on v.id = k.id
  order by combined_score desc
  limit match_count;
$$;
